#!/bin/bash
# SWARM Deployment Commands - Run these step by step

# Save the generated keys
SESSION_SECRET="$(openssl rand -hex 32)"
ENCRYPTION_KEY="$(openssl rand -hex 32)"
ENCRYPTION_SALT="$(openssl rand -hex 32)"

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║              SWARM DEPLOYMENT COMMANDS                        ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "Run these commands in order. Follow the prompts for each."
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "STEP 1: Login to Railway"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "railway login"
echo ""
echo "→ This will open your browser. Authorize Railway CLI."
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "STEP 2: Initialize Railway Project"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "cd /home/user/SWARM-1"
echo "railway init"
echo ""
echo "→ Choose: Empty Project"
echo "→ Name it: swarm-api"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "STEP 3: Set Environment Variables"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "# Copy and paste your DATABASE_URL:"
echo "railway variables set DATABASE_URL=\"YOUR_NEON_CONNECTION_STRING\""
echo ""
echo "# Set security keys (generated above):"
echo "railway variables set SESSION_SECRET=\"$SESSION_SECRET\""
echo "railway variables set ENCRYPTION_KEY=\"$ENCRYPTION_KEY\""
echo "railway variables set ENCRYPTION_SALT=\"$ENCRYPTION_SALT\""
echo ""
echo "# Set Node environment:"
echo "railway variables set NODE_ENV=\"production\""
echo "railway variables set PORT=\"5000\""
echo ""
echo "# Set your AI API keys (paste your actual keys):"
echo "railway variables set OPENAI_API_KEY=\"YOUR_OPENAI_KEY\""
echo "railway variables set ANTHROPIC_API_KEY=\"YOUR_ANTHROPIC_KEY\""
echo "railway variables set GEMINI_API_KEY=\"YOUR_GEMINI_KEY\""
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "STEP 4: Deploy Backend to Railway"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "railway up"
echo ""
echo "→ This will take 2-3 minutes. Watch the build logs."
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "STEP 5: Generate Public Domain"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "railway domain"
echo ""
echo "→ This creates a public URL for your backend."
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "STEP 6: Run Database Migrations"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "railway run npm run db:push"
echo ""
echo "→ This creates all database tables."
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "STEP 7: Get Your Backend URL"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "railway status"
echo ""
echo "→ Copy the URL (e.g., https://swarm-api-production-xxx.up.railway.app)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "STEP 8: Login to Cloudflare"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "wrangler login"
echo ""
echo "→ This will open your browser. Authorize Wrangler."
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "STEP 9: Build Frontend with Backend URL"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "# Replace with your actual Railway URL:"
echo "export VITE_API_URL=\"https://your-backend.up.railway.app\""
echo "npm run build"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "STEP 10: Deploy to Cloudflare Pages"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "wrangler pages deploy dist/public --project-name=swarm"
echo ""
echo "→ This deploys your frontend to Cloudflare's global CDN."
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "🎉 DEPLOYMENT COMPLETE!"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Test your deployment:"
echo "1. Backend health: curl YOUR_RAILWAY_URL/api/health"
echo "2. Visit your Cloudflare Pages URL"
echo "3. Create a test workflow"
echo ""
