name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for suggesting a feature!
        Features with the most 👍 reactions will be prioritized for implementation.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature
      placeholder: What would you like to see implemented?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "Example: I'm always frustrated when... OR I need to... but can't currently"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution and how users would interact with it
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Provide a specific example of how you would use this feature
      placeholder: "Example workflow or scenario where this feature would be used"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternatives or workarounds?
      placeholder: Describe any alternative solutions you've considered
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Workflow Builder Enhancement
        - Execution Engine Feature
        - AI Provider Integration
        - GitHub Integration
        - UI/UX Improvement
        - Templates & Marketplace
        - Knowledge Base
        - Scheduling & Automation
        - Webhooks & Triggers
        - Analytics & Monitoring
        - Collaboration Features
        - Security Enhancement
        - Performance Optimization
        - Developer Tools
        - Documentation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of this feature?
      options:
        - label: Saves time
        - label: Reduces costs
        - label: Improves reliability
        - label: Enhances security
        - label: Better user experience
        - label: Enables new workflows
        - label: Increases productivity

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Assessment)
      description: How important is this feature to you?
      options:
        - Critical - Blocking my use of the platform
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Interesting idea
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort (If Known)
      description: How complex do you think this feature is?
      options:
        - Small (1-2 hours)
        - Medium (3-5 hours)
        - Large (6-10 hours)
        - Very Large (10+ hours)
        - Unknown
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Willingness to Contribute
      description: Would you be willing to help implement this feature?
      options:
        - label: Yes, I can implement this
        - label: Yes, I can help with testing
        - label: Yes, I can help with documentation
        - label: No, just suggesting the idea

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add mockups, screenshots, diagrams, or examples
      placeholder: Any other context that would be helpful
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        **👍 Upvote this issue if you'd also like to see this feature!**
        
        Features with the most votes will be prioritized for implementation.
