name: 📋 Task
description: Create a task for project work
title: "[TASK] "
labels: ["task"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Create a Task
        Use this template for general development tasks, maintenance, or project work.

  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: What needs to be done?
      placeholder: Clear description of the task
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Task Type
      description: What kind of task is this?
      options:
        - Development
        - Bug Fix
        - Refactoring
        - Testing
        - Documentation
        - Configuration
        - Maintenance
        - Research
        - Code Review
        - Deployment
        - Other
    validations:
      required: true

  - type: dropdown
    id: assignment
    attributes:
      label: Assignment Type
      description: How should this task be assigned?
      options:
        - Self-assigned (I will work on this)
        - Auto-assign (Let orchestrator assign)
        - Team assignment needed
        - Open for volunteers
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: Task Checklist
      description: Break down the task into actionable items
      placeholder: |
        - [ ] Step 1
        - [ ] Step 2
        - [ ] Step 3
      value: |
        - [ ] 
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this task?
      options:
        - Critical (Do immediately)
        - High (This sprint/week)
        - Medium (Next sprint)
        - Low (Backlog)
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: How long will this take?
      options:
        - XS (< 1 hour)
        - Small (1-2 hours)
        - Medium (3-5 hours)
        - Large (1-2 days)
        - XL (2+ days)
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component/Area
      description: Which part of the system does this affect?
      options:
        - Frontend
        - Backend
        - Database
        - Infrastructure
        - CI/CD
        - Documentation
        - Testing
        - Multiple areas
        - Other
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Are there any dependencies or blockers?
      placeholder: |
        - Depends on #123
        - Blocked by #456
        - Requires external resource
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will we know this task is complete?
      placeholder: |
        - Feature X works as expected
        - Tests pass
        - Documentation updated
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any other relevant information
      placeholder: Technical details, links, references, etc.
    validations:
      required: false
